# Generated by Django 5.0.6 on 2024-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app_v1', '0003_payslip_philhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='total_deduc',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
